-- FIND THE NUMBER OF EMPLOYEES IN THE employee TABLE
SELECT COUNT(emp_id)
FROM employee;

-- FIND HOW MANY EMPLOYEES HAVE SUPERVISORS
SELECT COUNT(super_id)
FROM employee;


-- FIND THE NUMBER OF FEMALE EMPLOYEES BORN AFTER 1970
SELECT COUNT(emp_id)
FROM employee
WHERE sex = 'F' AND birth_day > '1970-01-01';

-- FIND THE AVERAGE OF ALL EMPLOYEE'S SALARIES FOR MALE EMPLOYEES
SELECT AVG(salary)
FROM employee
WHERE SEX = 'M';

-- FIND THE SUM OF ALL EMPLOYEE SALARIES
SELECT SUM(SALARY)
FROM employee;

-- FIND OUT HOW MANY MALES AND FEMALES THERE ARE
SELECT COUNT(sex), sex
FROM employee
GROUP BY sex;

-- FIND THE TOTAL SALES OF EACH SALESMAN
SELECT SUM(total_sales), emp_id
FROM works_with
GROUP BY emp_id;

-- HOW MUCH DID EACH CLIENT SPEND
SELECT SUM(total_sales), client_id
FROM works_with
GROUP BY client_id;