-- WE USE JOINS TO COMBINE TABLES BASED ON A COMMON KEY BETWEEN THEM

-- LEFT -> RIGHT
-- THERE ARE 4 TYPES OF JOINS
-- INNER JOIN - RETURN ONLY WHEN BOTH TABLES HAVE VALUES, CANNOT BE NULL - COULD BE INTERPRETED AS INCLUDING ALL MATCHING ROWS IN BOTH TABLES
-- LEFT JOIN - CAN RETURN NULL - WHEN VALUES ARE NOT FOUND IN THE OTHER TABLE - ALSO COULD BE INTERPRETED AS INCLUDING ALL ROWS IN THE LEFT TABLE
-- RIGHT JOIN - INCLUDE ALL ROWS FROM THE RIGHT (SECOND) TABLE, WE DON'T CARE IF LEFT TABLE GETS NULL
-- OUTER JOINS GRAB ALL DATA IN BOTH TABLES


-- INNER JOIN
SELECT employee.emp_id, employee.first_name, branch.branch_name
FROM employee
JOIN branch
ON employee.emp_id = branch.mgr_id;


