-- ON DELETE SET NULL WILL NULL OUT THE ROW'S FOREIGN KEY LINKING TO THE PRIMARY KEY

-- ON DELETE CASCADE WILL REMOVE THE ENTIRE ROW FROM THE DEPENDENT TABLE LINKED VIA A FOREIGN KEY

-- DELETE FROM employee
-- WHERE emp_id = '102';

-- SELECT * FROM branch
-- WHERE mgr_id = 102;

